/* CREATE ROLE professores NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOBYPASSRLS CONNECTION LIMIT 10;
ALTER ROLE professores PASSWORD '123';
CREATE ROLE Rodrigo PASSWORD '0906';
DROP ROLE rodrigo;
CREATE ROLE rodrigo LOGIN PASSWORD '0906' IN ROLE professores;
CREATE ROLE rodrigo LOGIN PASSWORD '0906' ROLE professores;
CREATE TABLE teste (nome varchar);
GRANT ALL ON TABLE teste TO professores;
CREATE ROLE rodrigo INHERIT LOGIN PASSWORD '0906' IN ROLE professores;
REVOKE professores FROM rodrigo;
*/


